### ISSUE TITLE
NPE in gll.clj

### ISSUE THREAD

**Issue by killme2008** [Engelberg/instaparse#102]
We use instaparse to parse a SQL-like language.Today i found an exception in our log:

```
uluru.log.2015-05-23_14-java.lang.NullPointerException
uluru.log.2015-05-23_14-	at clojure.core$subs.invoke(core.clj:4591)
uluru.log.2015-05-23_14-	at instaparse.gll$string_case_insensitive_parse.invoke(gll.clj:510)
uluru.log.2015-05-23_14-	at instaparse.gll$_parse.invoke(gll.clj:75)
uluru.log.2015-05-23_14-	at instaparse.gll$push_listener$fn__14111.invoke(gll.clj:276)
uluru.log.2015-05-23_14-	at instaparse.gll$step.invoke(gll.clj:328)
uluru.log.2015-05-23_14-	at instaparse.gll$run.invoke(gll.clj:344)
uluru.log.2015-05-23_14-	at instaparse.gll$run.invoke(gll.clj:332)
uluru.log.2015-05-23_14-	at instaparse.gll$parse.invoke(gll.clj:758)
uluru.log.2015-05-23_14-	at instaparse.core$parse.doInvoke(core.clj:83)
uluru.log.2015-05-23_14-	at clojure.lang.RestFn.invoke(RestFn.java:425)
uluru.log.2015-05-23_14-	at instaparse.core.Parser.invoke(core.clj:118)
```

We are using instaparse 1.3.3,and it looks that the exception was thrown by this line in gll.clj

https://github.com/Engelberg/instaparse/blob/v1.3.3/src/instaparse/gll.clj#L510

It looks that the `text` parameter is null. The expression to be parsed here may be in error syntax,and we will check it.But i think instaparse should throw a syntax error exception instead of NPE here.

**Comment by Engelberg** [comment]
That's puzzling.  That `text` parameter should just be the thing you're parsing, so it's not obvious to me how it could get to be null unless you're trying to parse `nil` or something along those lines.  So my best guess is that it's not really a syntax error, but something farther upstream is calling parse with a completely invalid input.  Any idea what input caused this error?

**Comment by killme2008** [comment]
The user does not provide the input expression right now. If it's our application code error, i will close this issue, thanks for your response.

**Comment by Engelberg** [comment]
It's always hard to know for sure, but I do think that's the most likely explanation.  `text` really should just be thing you're parsing, so I'd start by looking at your app code and see if you can find a way that your app would end up parsing nil.

**Comment by Engelberg** [comment]
I'm closing this for now, let me know if you discover any further indication that this needs to be explored from the instaparse side.
