### ISSUE TITLE
support escape characters in parser definition

### ISSUE THREAD

**Issue by carocad** [Engelberg/instaparse#110]
Hello Engelberg,
I might be wrong on this, but so far I have not been able to escape the characters that instaparse uses for the grammar definition. In my case, I am trying to create a variable with the name "<name>" but since instaparse uses "<" ">" as a way of omiting the tag, then I am force to use something else.

Note: In my case, it is not possible to put a name and later use insta/transform since I am building the parser grammar programatically and I don't know in advance the name of the tag that I would have to transform.

Of course there are workarounds, but I just wanted to know if there is a way or if you are planning to support it?

Thanks

**Comment by aengelberg** [comment]
Using < and > in terminal names seems to work when using the combinators to build a parser:
```clojure
=> (require '[instaparse.core :as insta] '[instaparse.combinators :as comb])
=> (def p (insta/parser [:<S> (comb/alt (comb/string "a") (comb/cat (comb/string "a") (comb/nt :<S>)))]))
#'user/p
=> (p "aaa")
[:<S> "a" [:<S> "a" [:<S> "a"]]]

**Comment by Engelberg** [comment]
This wasn't something I had ever considered supporting.  Adding escape characters for the special characters would significantly add to the complexity of the grammar spec.  As Alex points out, if you're generating the grammar programmatically, there are some good reasons to use the combinators -- it's much safer and gives you finer control than building up your grammar as a string -- and the combinators support arbitrary rule names.

**Comment by carocad** [comment]
I could confirm that in fact using the combinators works as mentioned with all kinds of keywords :)
