### ISSUE TITLE
(?i) in cyrillic

### ISSUE THREAD

**Issue by wwall** [Engelberg/instaparse#119]
hello.
in code  
>((insta/parser "S=#'(?i)перем'") "перем")
all work fine, but for 
>((insta/parser "S=#'(?i)перем'") "Перем")
i have error = 
Parse error at line 1, column 1:
Перем
^
Expected:
#"(?i)перем" (followed by end-of-string)

how i can add support case-insensitive for cyrillic letter?

**Comment by aengelberg** [comment]
This is an [issue](http://stackoverflow.com/questions/16659282/java-case-insensitive-regex-matching-doesnt-work-with-letter-%C3%91) with regexes. You can solve this by also adding the `(?u)` flag:
```
(def p (insta/parser "S = #'(?i)(?u)перем'"))

(p "Перем")
;; => [:S "Перем"]
```
The `:string-ci` feature of instaparse also works:
```
(def p (insta/parser "S = 'перем'" :string-ci true))

(p "Перем")
;; => [:S "перем"]
```
