### ISSUE TITLE
Interpreting Failure's when parens don't match

### ISSUE THREAD

**Issue by muhuk** [Engelberg/instaparse#121]
I am parsing a lisp-like syntax and trying to provide user-friendly error messages using `Failure` object and the original text. I use `:index` to figure out line/col info (via `instaparse.line-col/make-line-col-fn`) and  also try to calculate the text near `:index`.

I have two things I would like to improve on:

1. The error message on `Failure` is not something I can use as is:

        Parse error at line 5, column 1:

        ^
        Expected one of:
        ")"
        "("
        "["
        #"\w[\w\d-]*"
        #"\s+"

  I would instead like to show something like "unmatched parenthesis" (when the index is the end of text) or "a closing parent or this or that must follow". (Same thing just natural language.)

2. In the case of a missing closing paren index points to the end of text. Again if this was an internal thing I would be happy to get the informative `Failure`. However I am wondering if I can somehow get the `:starting-index` of where the unmatched paren is placed? (When the text is parsed without errors, we get this info, when there are errors it seems we only get `:index` where the cursor last was.)

-----

I am just asking if there is something obvious I am missing. Feel free to close this if it's out of scope. In any case Instaparse has been great help.

Also I would appreciate any insight about how to provide good error messages for unmatched parenthesis. Perhaps I can write a separate parser that just checks parens and pre-parse text with that.

**Comment by Engelberg** [comment]
Have you tried parsing in :total mode?  If you do that, you'll get the parse tree with the failure object as a node in the tree.  This should allow you to figure out that it is an unmatched paren, and extract the unmatched paren's position with `span`.

**Comment by muhuk** [comment]
Thanks a lot for the answer @Engelberg !

I have turned on `:total` mode and run some examples. It is quite cool, I can still get the `Failure` object using `insta/get-failure`. I still have a few questions.

Here are a few runs:

    "(x [)"
    [:PROGRAM [:instaparse/failure "(x [)"]]

    "(x (y)"
    [:PROGRAM [:APPLICATION "(" [:SYMBOL "x"] [:WHITESPACE " "] [:APPLICATION "(" [:SYMBOL "y"] ")"] [:instaparse/failure ""]]]

    "(x [y]"
    [:PROGRAM [:APPLICATION "(" [:SYMBOL "x"] [:WHITESPACE " "] [:LIST "[" [:SYMBOL "y"] "]"] [:instaparse/failure ""]]]

I know it would've been much better if you could see the entire thing, but I hope the examples above makes sense. From a parsing standpoint `:LIST` & `:APPLICATION` is the same thing, one with `()` and the other with `[]` (later on LISTs are treated as quoted lists).

1. For the first case, there's not much to work with. It says line 1, column 5, near ")". It seems I can say the last open paren ("[") before `:index` is where I should point to. Does that sound reasonable?
2. When we have `[:instaparse/failure ""]` it seems the action to take is to walk the tree, find the not with `:instaparse/failure`, walk up, point to the beginning. I can't think of another case where I would get `[:instaparse/failure ""]`. (Parser is quite simple `APPLICATION = "(" (WHITESPACE | ATOM | LIST | APPLICATION)* ")"` etc.)

I'm also wondering if there is a way to redesign the grammar to avoid special casing stuff.

Thanks again. I'm closing this but would love to get your opinion if you don't mind.

**Comment by muhuk** [comment]
I wanted to share my solution:


```clojure
    (require '[clojure.zip :as zip])


    (defn find-error-node [tree]
      (loop [z (zip/vector-zip tree)]
        (if (and (zip/branch? z)
                 (= :instaparse/failure (first (zip/node z))))
          (let [^String contents (second (zip/node z))]
            (if-not (.isEmpty contents)
              (zip/node z)
              (zip/node (zip/up z))))
          (recur (zip/next z)))))
```

If the goal is just to get to the failure node, `walk` works too. But I wanted to get to the failure node's parent if the contents are empty.

**Comment by Engelberg** [comment]
Glad you found a good solution.  Thanks for sharing.
