### ISSUE TITLE
Advice on parsing multiple formats

### ISSUE THREAD

**Issue by Immortalin** [Engelberg/instaparse#123]
Hi, I am trying to obtain the main words from the output of a crowd sourced spelling list and I am wondering if you can give me some advice on handling multiple formats.  There are five main formats with a couple other obscure formats scattered throughout the dataset(dataset is about 1000-2000 entries)

First format: (Merriam Webster, main word: gestalt, format consists of 75-80% of the dataset)
```sh
ge·stalt\gə-ˈstält, -ˈshtält, -ˈstȯlt, -ˈshtȯlt\
noun
psychology : something that is made of many parts and yet is somehow more than or different from the combination of its parts ; broadly : the general quality or character of something
Full Definition
: a structure, configuration, or pattern of physical, biological, or psychological phenomena so integrated as to constitute a functional unit with properties not derivable by summation of its parts
Other forms: plural ge·stalts also ge·stalt·en \-ˈstäl-tən, -ˈshtäl-, -ˈstȯl-, -ˈshtȯl-\
Origin: German, literally, shape, form.
First use: 1922
```

Second format(Wikipedia, main phrase: Account planning, 5% of dataset)
```sh
Account planning
Page issues
Account planning brings the consumer into the process of developing advertising. Planning is a job function relating to the application of strategy and planning techniques to direct brands unique direction across communications across advertising and marketing channels. The Account Planner, or simply Planner, has a role to identify and empathise with the target market and unlock insight that creates value between the consumer, the brand and the category of Product_(business) or service. The thoughts and observations are construed into a value proposition and make up a document called a Creative Brief that is used to create to inspire advertising campaigns and other marketing communications.
```

3rd format(Google Search, main phrase: churlish, 5% of dataset)
```sh
churlish

ˈtʃəːlɪʃ/

adjective

rude in a mean-spirited and surly way.

"it seems churlish to complain"
```
Google Search (main word: profundity, 5% of dataset)
```sh
Profundity 
noun, plural pro·fun·di·ties for 2, 3.

the quality or state of being profound; depth.
Usually, profundities. profound or deep matters.
a profoundly deep place; abyss.
```
5th format (dictionary.com, main word:transmogrify, 5% of dataset)
```sh
transmogrify
tranzˈmɒɡrɪfʌɪ,trɑːnz-,-ns-/
verbhumorous
verb: transmogrify; 3rd person present: transmogrifies; past tense: transmogrified; past participle: transmogrified; gerund or present participle: transmogrifying

    transform in a surprising or magical manner.
    "his home was transmogrified into a hippy crash pad"
```

What is the best way to write a parser that can handle all five entries? I have considered reducing the size of each entry by taking only the first three lines and parsing them but I am not sure whether that is the best way to do so.

**Comment by Engelberg** [comment]
If you have a way to chop the file into individual entries, and pass one entry at a time to the parser, that will certainly perform better.

Once you are working on individual entries, provided the formats look sufficiently distinct from one another, I'd think you could just list how to parse each format, give a list of alternatives, and let instaparse work it out, i.e.,

```
Entry = Format1 | Format2 | Format3 | ...
Format1 = ...
Format2 = ...
...
```

**Comment by Immortalin** [comment]
The entries are separate.

**Comment by Immortalin** [comment]
@Engelberg I am not sure whether this is the right place to ask but is it better to use Awk or Perl for this? Building up the grammars so far has been...painful and I am having second thoughts regarding using EBNF to parse a spelling list.

**Comment by Engelberg** [comment]
I'm not sure what to tell you.  Instaparse is specifically designed with the purpose of making it easy to turn an EBNF specification into an executable parser.  EBNF specs are only possible when the grammar is "context-free", and not all parsing tasks are.  Also, if you don't already have an EBNF spec, it can sometimes be hard to write one yourself, depending on your experience and the task at hand.  Instaparse's lack of a tokenization pass is an advantage for many applications, a disadvantage for some.

So if you are finding it difficult to model your parser in EBNF, it is entirely possible that it is, in fact, a difficult problem, and you are better off using a different technology.  ANTLR is one of the most professional-grade parsing tools in the Java ecosystem.  There are a lot of other parsing libraries out there with varying strengths and weaknesses.  Feel free to explore other options.
