### ISSUE TITLE
Transform don't touch instaparse.auto-flatten-seq.FlattenOnDemandVector nodes

### ISSUE THREAD

**Issue by sadchi** [Engelberg/instaparse#129]
After using parser i got a tree with some FlattenOnDemandVector. Nodes with such vectors are not processed with transform function. 

1. Let s say we have tree [:doc [:row "test string] #object[instaparse.auto-flatten-seq.FlattenOnDemandVector]]. FlattenOnDemandVector also contains row. 
2. Apply (intaparse/transform {:row str} tree) 
3. The first row is transformed, the second is not
How to solve this?

**Comment by Engelberg** [comment]
I would expect transform to work on FlattenOnDemandVector, because FlattenOnDemandVectors are meant to mimic regular vectors in every possible way.  So this sounds like it could be a bug.  Can you send me a concrete example?

**Comment by sadchi** [comment]
Thanks for the fast reply. 
I wrongly posted clj instaparse , but wanted to the cljs port of it. Sorry for that.
Your library works as expected (tested with repl).

**Comment by Engelberg** [comment]
Yes, report it to the cljs github page.  It's probably something that can be easily fixed, most likely the data structure needs to implement some protocol that it isn't currently implementing.  There isn't a lot of good documentation on what protocols need to be implemented by a data structure to mimic the built-ins, and it varies on Clojure vs Clojurescript so it is not trivial to port that piece.
