### ISSUE TITLE
Negative Lookahead not greedy enough

### ISSUE THREAD

**Issue by whamtet** [Engelberg/instaparse#132]
```clojure
((insta/parser "
               start = ((!'x' wildcard) * 'x') * (!'x' wildcard) *
               wildcard = #'[\\W\\w]'
               ")
 "h x h")

[:start [:wildcard "h"] [:wildcard " "] "x" [:wildcard " "] [:wildcard "h"]]
```

However if we change to

```clojure
((insta/parser "
               start = ((!'x' wildcard) * 'x') * wildcard *
               wildcard = #'[\\W\\w]'
               ")
 "h x h")

[:start [:wildcard "h"] [:wildcard " "] [:wildcard "x"] [:wildcard " "] [:wildcard "h"]]
```

If ((!'x' wildcard) * 'x') is truly greedy it should produce the same result as the first case.

**Comment by aengelberg** [comment]
Greedy behavior can only be expected if the star is inside the regex. For
example, #'a*' is greedy, #'a'* is not. The latter can match any number
(zero or more) of "a"s with no guaranteed preference.

**Comment by whamtet** [comment]
Ok, might be a good idea to clarify this in the documentation.

**Comment by fhur** [comment]
It is specified @whamtet: https://github.com/Engelberg/instaparse#regular-expressions-a-word-of-warning

**Comment by whamtet** [comment]
No you don't.  You emphasise the greediness of regular expressions.  I
suggest you draw a distinction with the non regex star operator to make it
explicit
