### ISSUE TITLE
(ABNF) repetition does not repeat the entire group

### ISSUE THREAD

**Issue by Whoops** [Engelberg/instaparse#134]
I found this attempting to use the grammer for IPv6 addresses defined in [RFC5954](http://www.rfc-base.org/txt/rfc-5954.txt). It appears when using groups, Instraparse does not expect a repetition of the entire group. For example `test = 2(DIGIT ":")` should match a digit followed by a colon twice, for example `1:1:` instead:
```clojure
(defn parse-test [data] 
                (let [parse (parser "test = 2(DIGIT \":\")"
                                    :input-format :abnf)]
                  (parse data)))
#'dmarced.core/parse-test
dmarced.core> (parse-test "1:")
[:test [:DIGIT "1"] ":"]
dmarced.core> (parse-test "1:1:")
Parse error at line 1, column 1:
1:1:
^
```

**Comment by aengelberg** [comment]
Thanks for finding this bug, I've opened a pull request to address it.

**Comment by Engelberg** [comment]
This has now been deployed as instaparse 1.4.2.
