### ISSUE TITLE
Requiring instaparse.core causes large spike in CPU usage

### ISSUE THREAD

**Issue by daveyarwood** [Engelberg/instaparse#146]
I'm hoping someone might have some insight on a major problem we're having with Alda, which relies on instaparse: https://github.com/alda-lang/alda/issues/266  In testing, I believe some part of instaparse may be the culprit.

To summarize: we are forking 4 worker processes upon startup of an Alda server. For about 10-15 seconds during startup, we're seeing the CPU usage of all 4 worker processes spike dramatically (~150-200% CPU on my 2014 Macbook), before decreasing down to about 2-3% and staying there.

The problem is difficult to profile mostly because I'm bad at profiling 😅  (I fumbled with `jvisualvm` and couldn't find an answer), but also because the CPU spike occurs only briefly while the Alda worker processes are starting up -- it's not like the CPU is just staying elevated and I can grab the top CPU consuming thread from the thread dump and see what it is.

So, in lieu of proper profiling, I've started experimenting with commenting out code and observing the CPU usage.

I was able to put together this base case which shows that requiring the `instaparse.core` namespace causes the spike: https://github.com/alda-lang/alda/blob/233d95e0da68d2a1003a1bb7c9f249d18b8e885c/server/src/alda/worker.clj 

(In the example above, the instaparse require is commented out -- to reproduce, uncomment it and comment out the taoensso.encore require.)

Requiring other namespaces (with the exception of timbre/encore) does not have the same effect.

I spent a little time building instaparse locally and commenting out parts of instaparse.core, and it looks like at least one source of CPU spiking is in instaparse.gll, but I couldn't dig much deeper without going down a major rabbit hole. Is anyone aware of any potential sources of heavy CPU usage in the instaparse codebase? (Or, would someone with profiling experience be willing to take a look?)

Any help is appreciated!

**Comment by Engelberg** [comment]
Offhand, I can't think of anything in instaparse that would be doing a lot of work (other than just usual Clojure compilation) when required.  And I can't think of any reason why it would behave differently if loaded on multiple threads.

I think @aengelberg has boot setup on his machine; I'll ask him if he can try out your test.

**Comment by daveyarwood** [comment]
Thinking about this a little more, I think this might be more to do with the way we're spawning multiple child processes at the same time from the main process. Each process is a separate process with its own JVM and Clojure runtime, so a significant number of things do need to load. I did notice that starting only one worker process causes a much smaller spike in CPU, ~30-40%. So perhaps the real problem is that we're trying to start 4 of these processes at once. I think staggering the worker startups could work as a workaround.

I am curious about what is causing the CPU usage though... when I have some time, I might take another stab at profiling. I'll let you know if I find anything CPU-intensive in instaparse!

**Comment by daveyarwood** [comment]
I tried spacing apart the starting of the workers by about 5 seconds, and CPU usage was much lower -- I think what I'm seeing is not instaparse-related after all, but just what happens when you try to start 4 Clojure processes at the same time! I'll close this issue.
