### ISSUE TITLE
insta/parser no longer reads java.net.URL objects in Clojure

### ISSUE THREAD

**Issue by scstarkey** [Engelberg/instaparse#152]
Not sure if you meant v1.4.4 to be backwards-incompatible with v1.4.3, but it is. Consider this code:

`(def ^:private parse-using-ebnf
  (insta/parser (io/resource "commands.ebnf") :string-ci true))`

In v1.4.3, this loads fine. However, in v1.4.4 I get a NullPointerException.

Instead, I must write:

`(def ^:private parse-using-ebnf
  (insta/parser (.toString (io/resource "commands.ebnf")) :string-ci true))`

**Comment by scstarkey** [comment]
Excellent! Thanks!!

**Comment by Engelberg** [comment]
Yeah, we'll be pushing that fix out soon, most likely later today.
