### ISSUE TITLE
auto-whitespace works with insta/parse but not (for me) with insta/parses

### ISSUE THREAD

**Issue by martinodb** [Engelberg/instaparse#153]
Hello!

I'm using auto-whitespace for my grammar, which is in a separate file. With insta/parse, it works like charm, but with insta-parser I get an error message.

IOW, this piece of code works:

```
(def parse-wg-martintest-1
    (insta/parser  (slurp "../grammar-martintest-1.ebnf") :auto-whitespace :standard ))
```
...but this one doesn't:

```
(def parses-wg-martintest-1
    (insta/parses  (slurp "../grammar-martintest-1.ebnf") :auto-whitespace :standard ))
```

The error I get is:

```
$ lein run
Exception in thread "main" java.lang.IllegalArgumentException: No value supplied for key: :standard, compiling:(core.clj:42:1)
```
I'm using instaparse 1.4.5
I'm new, sorry if I'm missing something obvious. Thanks in advance!

**Comment by aengelberg** [comment]
Auto whitespace must be provided at the time the parser is created. So
insta/parser works, but insta/parse and insta/parses do not.

**Comment by martinodb** [comment]
Oops, my bad. Thanks!
