### ISSUE TITLE
* before

### ISSUE THREAD

**Issue by Pitometsu** [Engelberg/instaparse#156]
BNF from RFC https://www.ietf.org/rfc/rfc2396.txt throw lot of errors.

**Comment by arrdem** [comment]
Yeah, Instaparse doesn't support this RFC's strange leading `n*....` notation for N or more repetitions. The traditional notation for this would be `....{n,}`. It actually doesn't look like Instaparse supports that either. Skimming the RFC however it looks like most of the leading `*` notation could be refactored using `*?` or `+?`.

**Comment by Pitometsu** [comment]
Yes, I replaced `*()` by `()*` and `1*()` by `()+`. I hope, it's correct. Just put it here in case you want to add that notation as well.

**Comment by Engelberg** [comment]
The n* notation is supported by ABNF, but not EBNF.

**Comment by Pitometsu** [comment]
But with `:input-format :abnf` I have error with that bnf from rfc:
```
   Error parsing grammar specification: Parse error at line 1, column 31:
   URI-reference = [ absoluteURI | relativeURI ] [ '#' fragment ] ^ Expected one
   of: ] / #"#\"[^\"\\]*(?:\\.[^\"\\]*)*\"(?x) #Double-quoted regexp"
   #"#'[^'\\]*(?:\\.[^'\\]*)*'(?x) #Single-quoted regexp" !  & % ' " [ < (
   #"[a-zA-Z][-a-zA-Z0-9]*(?x) #identifier" * #"[0-9]"
```

**Comment by Engelberg** [comment]
ABNF doesn't support the `|` character, which is in the grammar.

There are a lot of subtle variations in grammars, and I think the problems you are running into stem from the fact that this particular spec uses a hybrid of notations from EBNF and ABNF.

If you're looking for ABNF for URI, you might get farther with this as your starting point:
https://tools.ietf.org/html/rfc3986#page-49

**Comment by Engelberg** [comment]
Actually, there's already a tested URI spec in the test/data directory of instaparse.

**Comment by Engelberg** [comment]
If you're working on ABNF extensively, see issue https://github.com/Engelberg/instaparse/issues/136

As one user pointed out, a lot of ABNF grammars are actually ambiguous and assume left-to-right processing, but instaparse process alternatives right-to-left.  I'll likely be changing this in the next major point release of instaparse for better handling of these grammars that make this assumption.

**Comment by Pitometsu** [comment]
@Engelberg thanks a lot for suggestions. So, closing the issue for now.
