### ISSUE TITLE
Spaces in Non-Terminal Symbols?

### ISSUE THREAD

**Issue by aryeh-looker** [Engelberg/instaparse#159]
The Wikipedia page for EBNF describes several examples where non-terminal symbols have spaces in their names (https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form#Basics). Could it make sense for `instaparse` to support these kinds of symbols?

```
aryeh-db.core=> (print grammar)
digit excluding zero = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
digit                = "0" | digit excluding zero ;nil
aryeh-db.core=> (insta/parser grammar :input-format :ebnf)

RuntimeException Error parsing grammar specification:
Parse error at line 1, column 7:
digit excluding zero = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
      ^
Expected one of:
=
::=
:=
:
(*

  sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
```

**Comment by arrdem** [comment]
Probably not. Supporting non-terminals containing whitespace in their names leads to semantic ambiguity between concatenation and extended words. Consider a grammar like

```
a := "a"
b := "b"
foo := "foo"
a b foo := "bar"
qux := a b foo
```

What is qux? Is it `"bar"`? Is it `"abfoo"`? Why would you introduce this pitfall into a currently working tool, in support of a "grammar" "feature" in a language family for which everyone defines their own spec?

My $0.02 is to just refactor your grammar(s) to use names which are actually context insensitive. Yeah it sucks. Yeah I wish there were consistent specs for (E)BNF. Yeah I wish I could plug and play more grammars. But making Instaparse context sensitive like this would be a huge misfeature.

**Comment by aryeh-looker** [comment]
Cool! I agree. Thanks for such a cogent explanation.
