### ISSUE TITLE
Should throw exception?

### ISSUE THREAD

**Issue by cloojure** [Engelberg/instaparse#161]
Hi - I noticed that when there is a parse failure instaparse returns an instance of `instaparse.gll.Failure` instead of throwing an exception.  It seems it would be easier to process errors if they resulted in a normal Exception subclass.

Is this not something you wish to use?

Alan

**Comment by Engelberg** [comment]
Check out discussion here:
https://groups.google.com/d/msg/clojure/raxYhqEZb-4/IR4grWpgjHwJ
