### ISSUE TITLE
Iterate over partial parses before Garbage Collection?

### ISSUE THREAD

**Issue by combinatorist** [Engelberg/instaparse#162]
I am optimizing a home-made (BigQuery) SQL parser that works with simple queries, but runs out of memory parsing a complex query. I am sure this is because my grammar is ambiguous, but it's hard to debug because it doesn't return intermediate results.

Obviously, since I can't get a single parse, `insta/parses` also runs out of memory:
```OutOfMemoryError GC overhead limit exceeded  java.lang.Object.clone (Object.java:-2)```

I can run (`insta/parse ... :partial true)` and get the first (partial) parse, but what if I want the second result? 

I tried `insta/parses ... :partial true)`, but that also went to Garbage Collection without returning results. 

Is there a way to **iterate over `insta/parses` (with or without `:partial`) so that it returns intermediate results?** 

Without this, I don't know whether it's running out of memory because the grammar is so ambiguous or because it can't find a valid complete parse (only partials). Regardless, it would be nice to see at least two partial parses to get an idea of the ambiguity.

**Comment by Engelberg** [comment]
`parses` does produce a lazy sequence, so you should be able to give the result a name (e.g., `(def results (insta/parses ... :partial true))`) and then access the results one at a time using `(nth results 0)`, `(nth results 1)`, etc. causing them to get realized as you ask for them.  But that might not necessarily help because the explosion of memory could be due to tracking all the possibilities it will need to explore to produce the remaining elements of the sequence.

Have you tried looking for ambiguity on the simple examples that are working?  Try running `parses` on a simple example with `:unhide :all`, or consider [tracing](https://github.com/Engelberg/instaparse/blob/master/docs/Tracing.md) simple examples.

**Comment by combinatorist** [comment]
Oh, thank you, @Engelberg, I didn't realize it was a lazy sequence. I'll try that and I'm sure it will show me a few more (considering the first partial parse is instant - pun intended ;).

Also, I didn't know about trace or even think to look in https://github.com/Engelberg/instaparse/tree/master/docs for more functionality. 

I think between these various options, I should be able to debug my grammar efficiently. I suppose worst case scenario, I could raise my memory limit to get a few more partial parses if I need. 

Thank you for your help!

**Comment by combinatorist** [comment]
Ok, the first 2 results were very quick, but it's hanging on the third. Do you know - does it rerun the first 2 (internally) to generate the third, or is there a way to get it to "pause" with memory and just return 1 more each time?

**Comment by Engelberg** [comment]
Lazy sequences cache their elements, so it shouldn't need to recompute anything to move through the elements that were already realized.  It is effectively "pausing" with the whole state of what it needs to compute the next element(s).  So it's doing what you want.  But in an ambiguous grammar, that state can grow too large. Were you able to deduce anything from the first two outputs?  Is there a way to temporarily increase memory just for the purposes of getting the third element to analyze it.  Did you learn anything from looking at the "unhidden", complete parses of the smaller examples that work successfully?

**Comment by combinatorist** [comment]
I was able to make use of your debugging tricks and they helped but I haven't built a complete parser for BigQuery yet - go figure ;). 

FWIW, I started to look for SQL grammars already built, but I couldn't find any in EBNF (although there are lots on BNF). In fact, most of them were in locked up in some markdown language to display on a website which is makes even more baggage.

If I get a chance to return, then I'd like to post my BigQuery parser somewhere multiple people can contribute and continue to improve it. Do you know of any pure (instaparse dialect) EBNF repositories?

TBH, someone suggested ANTLR and I has some instant success because it gave me access to some complete parsers for other SQL dialects that appeared to be really performant. I'm planning to adjust one of those to work with BigQuery rather than create it from scratch. Granted, ANTLR is not as flexible as instaparse, but the flexibility is what's creating ambiguity and performance issues.
