### ISSUE TITLE
Warning with Clojurescript

### ISSUE THREAD

**Issue by philjackson** [Engelberg/instaparse#165]
WARNING: EMPTY already refers to: cljs.core/EMPTY being replaced by: instaparse.auto-flatten-seq/EMPTY at line 23 target/cljsbuild/public/js/out/instaparse/auto_flatten_seq.cljc

Presumably could cause issues.

**Comment by Engelberg** [comment]
What issues do you foresee?  Seems like this is mainly an informational warning that instaparse.auto-flatten-seq is shadowing a core name.  This wouldn't affect external code; it would only apply within the instaparse.auto-flatten-seq namespace, which doesn't rely on a cljs.core/EMPTY.

The weird thing is, I don't see any reference to EMPTY in the clojurescript source:
https://github.com/clojure/clojurescript/edit/master/src/main/cljs/cljs/core.cljs

**Comment by stevebuik** [comment]
This no longer happens under cljs version "1.9.908". 

There are two new warnings under that version, one of which is logged in https://github.com/Engelberg/instaparse/issues/170

**Comment by Engelberg** [comment]
Closing issue since it doesn't apply to recent versions of cljs.
