### ISSUE TITLE
how to get the body of a class

### ISSUE THREAD

**Issue by cjqw** [Engelberg/instaparse#166]
Hello,I'm working on a parser of a java-like language, but the auto-whitespace is annoying when I want to use #'.*' to match the body of a class. Here is the simplified grammar:

```
class-definition = "class" id "{" class-body "}" 
class-body = #".*"
id = #"[_a-zA-Z][_0-9a-zA-Z]*"
```
Here I want to get the body of the class and deal with it in somewhere else, but the regex cannot be matched correctly when auto-whitespace enabled. Here is a simple example:
```
class SampleClass{
    int foo(int x){
    }
}
```
The parser threw an error:
```
{:index 48,
:reason [{:tag :string, :expecting "class"}],
:line 4,
:column 1,
:text "}"
}
```
And when I changed #'.*' into #'.'*, the parser can get the content of the body, but some important whitespace is left, I guess the control logic of auto-whitespace can be enhanced to fix this problem.

**Comment by cjqw** [comment]
Sorry,I found that the problem may be caused by the regex. Then would someone give me a suggest on how to get the body of  the class?

**Comment by Engelberg** [comment]
You said: And when I changed `#'.'` into `#'.'`, the parser can get the content of the body, but some important whitespace is left...

I don't see a difference between those two regexes.  Maybe github ate some of your formatting.  Can you retype the regex that almost worked?

**Comment by Engelberg** [comment]
How about this regex?

     #"[^}]+?(?=\s*})"

This says "Do the shortest possible match of one or more non-`}` characters until you hit a run of zero or more spaces followed by a `}`.

This makes use of "non-greedy wildcards", i.e., `+?`, "negative character classes", i.e., `[^}]` and "positive lookahead", i.e., `(?=...)` if you want to look this stuff up.

**Comment by Engelberg** [comment]
And `\s` matches whitespace.

**Comment by cjqw** [comment]
Sorry,I mean change
```
#',*'
```
into
```
#'.'*
```
the problem is the regex matched too many characters,thanks for answering.
