### ISSUE TITLE
RegExp flags are ignored in ClojureScript

### ISSUE THREAD

**Issue by dundalek** [Engelberg/instaparse#171]
RegExp flags such as for case-insensitive matching are ignored in ClojureScript.

Here is a repro case:
```clojure
(ns example.core
  (:require [instaparse.core :as insta]))

(def insensitive
  (insta/parser
    "S = #'(?i)a'"))

(defn -main []
  (->> (insensitive "a") (clj->js) (js/console.log "lower case:\n"))
  (->> (insensitive "A") (clj->js) (js/console.log "upper case:\n")))

(set! *main-cli-fn* -main)
```

Which parses the lower case variant but fails on the upper case:
```
lower case:
 [ 'S', 'a' ]
upper case:
 { index: 0,
  reason: [ { tag: 'regexp', expecting: /^a/, full: true } ],
  line: 1,
  column: 1,
  text: 'A' }
```

JavaScript has different way to specify flags than Java, but I assume cljs uses some kind of macros for transformation because following works:
```
cljs.user=> (re-matches #"(?i)a" "a")
"a"
cljs.user=> (re-matches #"(?i)a" "A")
"A"
```
RegExps get transformed to js format:
```
cljs.user=> (str #"(?i)a")
"/a/i"
```

Could the RegExps be passed through cljs macros as well?

I am running using these versions:
```
[org.clojure/clojure "1.8.0"]
[org.clojure/clojurescript "1.9.562"]
[instaparse "1.4.7"]
```

**Comment by Engelberg** [comment]
Fixed in 1.4.9.  Thanks.
