### ISSUE TITLE
RFC 5234 and case issues

### ISSUE THREAD

**Issue by arrdem** [Engelberg/instaparse#174]
[RFC 5234](https://tools.ietf.org/html/rfc5234) which defines the basic ABNF grammar Instaparse implements and many specifications use states (2.3.  Terminal Values)

```
   Literal text strings are interpreted as a concatenated set of
   printable characters.

   NOTE:

      ABNF strings are case insensitive and the character set for these
      strings is US-ASCII.

   Hence:

         rulename = "abc"

   and:

         rulename = "aBc"

   will match "abc", "Abc", "aBc", "abC", "ABc", "aBC", "AbC", and
   "ABC".

      To specify a rule that is case sensitive, specify the characters
      individually.

   For example:

         rulename    =  %d97 %d98 %d99

   or

         rulename    =  %d97.98.99

   will match only the string that comprises only the lowercase
   characters, abc.
```

The [case sensitivity disclaimer](https://github.com/Engelberg/instaparse/blob/master/docs/ABNF.md#case-sensitivity) states that case insensitivity is achieved by normalizing to uppercase. While this is an acceptable implementation detail, exposing uppercased-normalized data may not lead to standards compliant implementations.

**Comment by Engelberg** [comment]
It's just the rule names, I believe, that are normalized to uppercase.  The actual string data is compared in a case insensitive way, but the data's case is retained, as I recall.

**Comment by Engelberg** [comment]
Does this address your concern?

**Comment by arrdem** [comment]
Testing confirms that source data capitalization is preserved. Yep we're all set here.
