### ISSUE TITLE
ABNF grammar hangs on bad input

### ISSUE THREAD

**Issue by jrwdunham** [Engelberg/instaparse#182]
I have an ABNF grammar that recognizes correct inputs but then just hangs and burns my CPU like crazy if I give it a bad input. Can anyone help me out? Details below. (This may be related to https://github.com/Engelberg/instaparse/issues/43.)

I have this ABNF grammar:

    payload-manifest = 1*p-m-line
    p-m-line         = checksum 1*WSP filename ending
    checksum         = 1*hex-val
    hex-val          = 1*case-hexdig
                     [ 1*("." 1*case-hexdig) / ("-" 1*case-hexdig) ]
    case-hexdig      = DIGIT / "A" / "a" / "B" / "b" / "C" / "c" / "D" /
                     "d" / "E" / "e" / "F" / "f"
    HEXDIG           = DIGIT / "A" / "B" / "C" / "D" / "F"
    filename         = (
                        "data"
                        "/"
                        1*( unreserved / pct-encoded / sub-delims )
                       )
    unreserved       = ALPHA / DIGIT / "-" / "." / "_" / "~"
    sub-delims       = "!" / "$" / "&#38;" / "'" / "(" / ")" / "*"
                     / "+" / "," / ";" / "=" / "/"
    pct-encoded      = "%" HEXDIG HEXDIG
    ending           = CR / LF / CRLF

and this sample input:

    76e096874a31e854ac093ea06531f7a91d97af8c7684a8ab0503d1c77080d6e3  data/METS.9b63e430-8fd7-4da4-b930-da5afe0ff32c.xml
    9a56155bec60ff8f5cb8f184b7dff23b01d24f4aa9aca7a4f0becb62349bc6b7  data/logs/fileFormatIdentification.log
    f5a5c3a52cce3fac27e85ebd5b4fa0820da4fa2f4d74ec4adfb86a726c6fa245  data/logs/filenameCleanup.log
    9cd9434ce7f6b0ccd35242964f405850e6142451aa7f326f4ad721987151b8a4  data/logs/transfers/vvv-646bfa86-7173-44f1-974d-b37e989d4064/logs/fileFormatIdentification.log
    ebabae9d199c2216b0bb2dc07b0ae68eefc32616aafdd284c5aa84ee34ac6391  data/logs/transfers/vvv-646bfa86-7173-44f1-974d-b37e989d4064/logs/filenameCleanup.log
    edeaaff3f1774ad2888673770c6d64097e391bc362d7d6fb34982ddf0efd18cb  data/objects/abc.txt
    e881ad3f2d2f34376978748b7e42d26bcbb39402b2e0b162378ab8aaa5ee8fbf  data/objects/submissionDocumentation/transfer-vvv-646bfa86-7173-44f1-974d-b37e989d4064/METS.xml
    0c154f83522f34dae671ce144318f6b2649ac06b1bebff99a66bcff2e0b4ffb9  data/thumbnails/43d4e638-2d89-4c00-9b56-5039f373b102.jpg

I have this test function:

    (deftest payload-manifest-test
      (testing "FIXED Payload Manifest grammar works as expected"
        (let [p-m (get-sample-payload-manifest)
              parse ((get-payload-manifest-grammar-fixed) p-m)]
          (is (vector? parse))
          (is (= :payload-manifest (first parse))))))

which uses these two funcs to get the grammar and the input from disk:

    (defn get-sample-payload-manifest
      []
      (slurp
        (clojure.java.io/resource "sample-manifest-sha256.txt")))

    (defn get-payload-manifest-grammar-fixed
      []
      (insta/parser (clojure.java.io/resource "payload_manifest_fixed.abnf")))

However, if I do something simple to make the input invalid (like add a newline to the end of the input file), my test function just never returns. Thoughts?

**Comment by Engelberg** [comment]
Probably, there are exponentially different ways to group the input based on this grammar, and if it doesn't fit the grammar at all, it has to exhaust all the possible groupings to prove that it is bad.

You could explore this hypothesis by looking at all possible parses of your text, to make sure it is unambiguous.

Also, it would help to shrink the error case as much as possible, with the hope that you can find something that, although slow, returns a parse or an error, and then we can try some of the tracing features to understand what it is doing.  So, maybe, for example, do a one-line sample input and then alter it with an added newline.  

If it's not vital to stick to the ABNF, I'd recommend rewriting this using the EBNF grammar and using regular expressions to define the checksum and filenames.  I think you'll get much better results that way.  Processing something like this character by character in instaparse is possible, but not ideal.

**Comment by jrwdunham** [comment]
Thanks for the explanation/hypothesis @Engelberg and also for the advice. Love the library by the way. I used it in a small way to debug the proposed BagIt AGNF specification for the (LoC's) archival package format specification. This is closable imo.
