### ISSUE TITLE
Feature Request: CLR version

### ISSUE THREAD

**Issue by JacobGood1** [Engelberg/instaparse#185]
Any plans on making a CLR version?

**Comment by arrdem** [comment]
Almost certainly not. ClojureScript support wasn't added until someone else implemented and PR'd it.

**Comment by JacobGood1** [comment]
I'm paying good money for this, I expect more from you. 😁

Ok, I understand, you can close this now

**Comment by Engelberg** [comment]
Sorry for not responding sooner. I have gotten rather busy and it's been hard to find time to respond to all the questions submitted through issues, and pull requests.  I try to respond to any bugs within 24 hours (and fortunately, there haven't been any in instaparse in a long time), but general questions often sit for a while until I get a free weekend.  @arrdem is right that Clojurescript was initiated as a separate port with its own github repository, and then started seeing enough use that @aengelberg took an interest in incorporating it directly into the main instaparse repository.  I have no hands-on experience with clojureCLR, so don't know what it would entail and can't take that on myself, but I would certainly support any community effort from people who want to make it happen.
