### ISSUE TITLE
Composable/reusable grammars

### ISSUE THREAD

**Issue by razum2um** [Engelberg/instaparse#188]
We can slurp grammar but I see no good way to compose 2 grammars together.

It would be cool if to have reusable pieces of grammars like ipv(4/6), emails, domain names, maybe even whole grammar to parse standard nginx access log, wouldn't it? Inspired by https://github.com/SparkFund/useful-specs

Suggesting a way to expose a var inside grammar is hard as both `/` and `.` are reserved. Maybe `_`, what do you think?
```
;; lib
(def useful.ebnf/parser (insta/parser "a = 'a' b; b = 'b'"))
;; code, approach#1
(insta/parser "s = useful_ebnf_a t; t = useful_ebnf_b" :import [useful.ebnf/parser])
;; code, approach#2
(insta/parser "s = a t; t = b" :import {:a useful.ebnf/parser :b useful.ebnf/parser}])
```

**Comment by Engelberg** [comment]
The current way to compose grammars is to use `instaparse.combinators/ebnf` or `instaparse.combinators/abnf` to turn grammars into maps, and then merge the maps.  `parser` then works on the merged map to produce a parser.  There is an example in this section of the doc:
https://github.com/engelberg/instaparse#string-to-combinator-conversion

I can't think of a nice way to expose a var inside the grammar that wouldn't potentially be a breaking change (nothing prohibits someone from using `_` in rule names, so anyone who has used that as a word separator would have problems.  I see the utility, but won't be considering it until I decide to make a version that breaks backwards compatibility, and I'm not sure when that will be.
