### ISSUE TITLE
Not working on clojurescript 1.10.439

### ISSUE THREAD

**Issue by galdolber** [Engelberg/instaparse#189]
One error I get is this:

<img width="376" alt="screen shot 2018-11-11 at 2 56 21 pm" src="https://user-images.githubusercontent.com/963214/48316404-febc4400-e5c1-11e8-8809-8b13b9a5a00f.png">

But even when I fixed that, the parser function is failing.

**Comment by Engelberg** [comment]
@galdolber Can you describe the way it is failing?  It appears that Clojurescript made a change to the public visibility of some functions, and added a new set of compiler warnings, but the warning should not break the function.  I would expect it to still work, as @mtruyens described.

**Comment by galdolber** [comment]
`
(instaparse.core/parser 
               "S = AB*
                AB = A B
                A = 'a'+
                B = 'b'+")
`

I get: 
<img width="540" alt="screen shot 2018-11-12 at 1 17 30 am" src="https://user-images.githubusercontent.com/963214/48326566-c6942000-e618-11e8-9fea-1bdc3be1b397.png">

**Comment by galdolber** [comment]
Just found something else. There seems to be a huge performance slowdown.

Under clojurescript 1.10.312:
<img width="574" alt="screen shot 2018-11-12 at 1 39 19 am" src="https://user-images.githubusercontent.com/963214/48327163-f7c21f80-e61b-11e8-9f33-d7c43b72e08d.png">

Under clojurescript 1.10.339:
<img width="693" alt="screen shot 2018-11-12 at 1 33 00 am" src="https://user-images.githubusercontent.com/963214/48327171-03154b00-e61c-11e8-8d2e-1106dea85a96.png">

**Comment by galdolber** [comment]
This is the commit that breaks the code:
https://github.com/clojure/clojurescript/commit/9a8196ebfe4265feda88a06de84affb9df469012

**Comment by galdolber** [comment]
I was able to fix the issues here: https://github.com/Engelberg/instaparse/pull/190

**Comment by Engelberg** [comment]
I fixed the warning that clojurescript was giving about the use of the private var `read-string*` from tools.reader.  But I am unable to duplicate the bug you are seeing.  The test suite is passing under the latest version of clojurescript, and I entered in your sample bug by hand into a clojurescript REPL and it worked fine.

I bumped up the version of tools.reader listed in the dependencies, so perhaps that helped.  Please check again against instaparse 1.4.10 and let me know whether you still see a problem.  Thanks for your assistance.

**Comment by jeroenvandijk** [comment]
I can confirm that upgrading from 1.4.9 to 1.4.10 got rid of the warning:

```
WARNING: var: cljs.tools.reader/read-string* is not public
```
Which blocked figwheel to compile my code.

Thanks! Btw the README still says 1.4.9 (hence my trial)

**Comment by Engelberg** [comment]
Just updated README. Thanks for catching that.
