### ISSUE TITLE
Allow escaping with negative lookahead

### ISSUE THREAD

**Issue by judepayne** [Engelberg/instaparse#194]
Struggling to see how to use negative lookahead to allow a user to escape in their text.

    (def regex-kvs  "#'[/\\+\\w\\d\\s\\n\\.\\(\\)@&:<>\\'#=/-]*'")

    (def csv-grammar
      (str
       "S = <'e:'> E 
        <KVs> = " regex-kvs "
        esc = #'\\\\'
        E = Node !esc <','> Node
        Node = KVs ?"))

    (defparser csv-line-parser
      csv-grammar
      :auto-whitespace whitespace)

    (csv-line-parser "e:pandas:simone,pandas:max")
    [:S [:E [:Node "pandas:simone"] [:Node "pandas:max"]]] .     ;; great

    (csv-line-parser "e:pan\\,das:simone,pandas:max")
    {:index 5,
      :reason
      [{:tag :negative-lookahead, :expecting {:NOT "esc"}}
       {:tag :regexp, :expecting #"\s+"}],
      :line 1,
      :column 6,
     :text "e:pan\\,das:simone,pandas:max"}

Any help would be much appreciated! Working in cljs, so having the grammar in a file is not an option.

**Comment by Engelberg** [comment]
I'm not clear on what behavior you want. Can you elaborate?

**Comment by judepayne** [comment]
Thanks for getting back so fast! I am looking for the user to be able to supply text in which the comma separator can be escaped. So in the second example above, I would be hoping for:

    [:S [:E [:Node "pan\\,das:simone"] [:Node "pandas:max"]]]

i.e. to have the string parsed with user supplied escaping in tact.

**Comment by Engelberg** [comment]
I believe this would need to be addressed at the regex level.  Work on crafting the regex-kvs to allow a comma character only when preceded by a backslash.  

The negative lookahead isn't really relevant here because the regex is what determines valid tokens. Your negative lookahead simply makes it illegal to have a backslash before a comma occurring between two nodes.

**Comment by Engelberg** [comment]
So, for example, `#"([abc]|(\\,))*` only allows the characters a, b, c, and a comma when preceded by a backslash.

**Comment by judepayne** [comment]
Thank you. I will take a look

**Comment by judepayne** [comment]
adapting regex-kvs to:

    (def regex-kvs  "#'([/\\+\\w\\d\\s\\n\\.\\(\\)@&:<>\\'#=/-]|(\\\\,))*'")

did the trick as per Mark's suggestion. Thanks again!
