### ISSUE TITLE
Syntax to "concat" many strings to one string

### ISSUE THREAD

**Issue by schoettl** [Engelberg/instaparse#203]
Hi @Engelberg,

we use instaparse in [org-parser](https://github.com/200ok-ch/org-parser). Thank you for this great parser generator but I think I just hit the limits of instaparse:

A regex `#".*"` parses too greedy, but `{ #"." }` parses a list of strings instead of one string.

4 years ago, this issue was addressed here and I think it's still the same:
https://stackoverflow.com/questions/36706854/instaparse-series-of-numbers-or-letters-as-one-leaf
My use case is more complicated, and I think I need to use BNF instead of a regex which parses too greedy.

How do you think about, adding new syntax to instaparse to fix this?

For example, additionally to `*  {}` and `+`, there could be a syntax
```
str = @concat { char }
str = #concat { char }
(* or a + symbol for "concat"? *)
str = char *+

(* where *)
char = #"."
```

Of course, I could concat the list of strings in a later transform step, but for unit-testing the parser, it would be very helpful to directly parse a single string.

I actually like instaparse's slim syntax. So something like a macro system like the first two syntax suggestions might be better? Maybe I overlooked an existing issue addressing this kind of "inline-code"?

**Comment by Engelberg** [comment]
Can you give a more complete description of what your tokens are?

Odds are good there's a way to implement the tokens in regexes. Regexes have a number of sophisticated options for non-greediness, lookahead and lookbehind, which make it well-suited to describing tokens.

If your tokens are genuinely too complicated for regexes, and you really need to think of each character as a token in your grammar, then that's a good argument for building your unit tests around the notion of individual characters as tokens, and to do transforming steps later.

https://www.regular-expressions.info/lookaround.html
https://www.regular-expressions.info/repeat.html
https://medium.com/@wpcarro/non-greedy-regular-expressions-7dfb5177d57e

**Comment by schoettl** [comment]
Thanks for the reply and links!

My specific problem, currently, is this:

Orgmode links[1] can look like this: `[[file:myfile.txt::15]]`
It is a link that jumps to the file on line 15.

Currently, for the part inside the brackets, I have[2]:
```
link-ext-file = <'file:'> link-inside-filename [ link-ext-file-location ]
<link-inside-filename> = #"[^]:]*"
<link-ext-file-location> = <'::'> ( link-file-loc-lnum / link-file-loc-headline / link-file-loc-customid / link-file-loc-string )
```

But this way, the filename can not contain `:` and the parser will fail on e.g. `[[file:my/file:name.txt::15]]`.

[1] https://orgmode.org/manual/External-Links.html#External-Links
[2] https://github.com/200ok-ch/org-parser/pull/9/files#diff-5701741f8bb85a219404fb9c408e7662R207

**Comment by Engelberg** [comment]
Thanks for the additional info. You'll need to play around with it to find the exact syntax, but I am reasonably confident that your token can be described by a regex.

Explore ways using lookahead or negative lookahead to express one of the following concepts:

link-inside-filename is a sequence of characters that are not `]` and not a `:` that is immediately followed by another `:`

link-inside-filename is a sequence of characters ending with one that is immediately followed by either `::` or `]]`.

**Comment by schoettl** [comment]
Thanks, I'll try your suggestions and links and report back.

I'm not fully convinced yet, because in `[[file:my/file::name.txt::15]]`, the filename actually contain `::`.

But I'll try. Maybe a multi-character look-ahead `:[^]:]+`, to make sure, the location part does not contain `:`...

**Comment by Engelberg** [comment]
Maybe you can formulate it as:
A sequence of characters until you reach `]]` or you reach a `::` which, looking ahead, we see is followed by a string of non-`:` characters and then `]]`

**Comment by schoettl** [comment]
Thank you Mark, regex look-arounds are pretty mighty :) It wasn't hard to solve in the end.

I understand that it's better to keep the EBNF as simple as possible (no concat "macros" that I suggested). It's actually also the goal of the org-parser project, to create a pure EBNF for orgmode.
