### ISSUE TITLE
Tagged inline concatenations with instaparse.combinators/cat

### ISSUE THREAD

**Issue by theronic** [Engelberg/instaparse#206]
Is there a way to tag rules passed to instaparse.combinators/cat without resorting to non-terminals, similar to how `clojure.alpha.spec/cat` syntax works? For example,

```
(c/cat
   :tag1 (c/rep 2 2 :digit) ;; where :tag1 is the tag
   :tag2 (c/rep 3 3 :digit) ;; where :tag2 is the tag
```

I'm finding it arduous to move each component of simple concatenation into its own rule on the left-hand side rule, especially when using combinators.

Would love to be able to do this:

```
(defparser test-parser
  {:S (cat
        :A (string "abc")
        :B (string "def")}
   :start :S)

(insta/parse test-parser "abcdef")
=> [:S [:A "abc"] [:B "def"]]
```

**Comment by Engelberg** [comment]
Sorry, there's no way to tag things other than to introduce the tag on the left-hand side of a rule.

One advantage of this approach is it lends itself to composing grammar maps, and the semantics of merging maps in Clojure provides clear semantics about how to resolve conflicts when two different grammar maps use the same tag in different ways.
