### ISSUE TITLE
Is there proper way to do exclusion in a CFG?

### ISSUE THREAD

**Issue by GlassGhost** [Engelberg/instaparse#213]
This isn't really an issue so much as a cry for help,
but perhaps something could be said in the readme on exclusion if there is an answer to this question

[A short introduction to the Lambda Calculus by Achim Jung](https://www.cs.bham.ac.uk/~axj/pub/papers/lambda-calculus.pdf)
listed a less ambiguous grammar for the lambda calculus

Without a strict grammar the term `\x.x y` could be parsed as With auxiliary 
brackets, the 2 possible interpretations can be indicated by writing `\x.(x y)` 
and `(\x.x) y`, respectively. According to convention, only the 1st 
interpretation should be possible.

    ;lambda.abnf_____________________________________________Lambda Calculus RFC2234
    ;(<Variable> / "(" <fun> ")") replacing <head−atom>
    ;and <Variable> replacing x from Achim Jung's grammar
        <term> = <fun> / <app> / <atom>
         <fun> = <LAMBDA>, <Variable>, ".", <term>
         <app> = (<Variable> / "(" <fun> ")"), <atom> / <app>, <atom>
        <atom> = (<Variable> / "(" <fun> ")") / "(" <app> ")"
    <Variable> = *((<AllUTF8Chars_Except_EscapableChars>) - <EscChars>)
    <EscChars> = "." / "(" / ")" / <LAMBDA> / <WSP>
      <LAMBDA> = %5C     ; \ for lambda should be %x03BB but this is a tutorial
         <WSP> = *( %x20 / %x0A / %x09) ;space, linefeed, or HTAB

I wrote grammar to parse the lambda cal in abnf, except for one thing:

    <Variable> = *((<AllUTF8Chars_Except_EscapableChars>) - <EscChars>)

This line uses a exclusion operator which to my knowledge makes the parser no longer a CFG

**Comment by Engelberg** [comment]
I'm not familiar with the `-` operator you're showing here, but it sort of looks like this is happening at the token level, trying to define all the characters that are not escape characters, which you can probably do with a regular expression. Negative lookahead might also be relevant, but should be used sparingly.

**Comment by GlassGhost** [comment]
Ok, I looked it up and according to https://www.cs.unc.edu/~plaisted/comp455/slides/cfl3.5.pdf

You cannot have exclusion in a cfg, and if you do it is no longer a cfg.

Which can make things a lot slower and more complicated or just plain old not work at all, which is why I think it wasn't included in abnf/ebnf

**Comment by GlassGhost** [comment]
This is correct right?

https://github.com/Engelberg/instaparse/issues/116

is negative lookahead a implementation of exclusion or a not operator?? is it still context free?

**Comment by Engelberg** [comment]
I am unfamiliar with the term "exclusion operator", so I can't answer that question directly, but yes, the whole point of negative lookahead is to scan ahead and only permit strings that do NOT satisfy some grammar rule starting from that point. This allows you to implement certain things that are not context free.
