### ISSUE TITLE
Information about rules used in a successful parse?

### ISSUE THREAD

**Issue by respatialized** [Engelberg/instaparse#214]
Hi there! I've really enjoyed using Instaparse, and so thank you for making such a great library available to the Clojure community.

I was interested in taking on some analysis of how often rules in a grammar get used to parse a string with that grammar. Taking the example of `abc` from the `README`:

```ebnf
S = &(A 'c') 'a'+ B
A = 'a' A? 'b'
<B> = 'b' B? 'c'
```
If I use `:unhide :all` when parsing, I get back:
```clojure
[:S "a" "a" "a" [:B "b" [:B "b" [:B "b" "c"] "c"] "c"]]
```
So I can tell from this that rule `B` was used three times and rule `S` was used once, but rule `A` is skipped in the final parse tree even though it contributed to a successful parse, which I think is due to its use in a lookahead in the starting production `S`. I believe the specific answer that I am looking for in terms of the question "how many times was rule `A` in grammar `abc` used to parse the string `aaabbbccc`?" is also 3, but that is not visible in the output.

It seems like that the information I want may be recoverable from the output of `:trace`, and indeed I observe `Result for A` 3 times a bit further down in the output.
<details><summary>Output of trace:</summary>
<pre>
Initiating full parse: S at index 0 (aaabbbccc)
Initiating full parse: &(A "c") "a"+ B at index 0 (aaabbbccc)
Initiating parse: &(A "c") at index 0 (aaabbbccc)
Initiating parse: A "c" at index 0 (aaabbbccc)
Initiating parse: A at index 0 (aaabbbccc)
Initiating parse: "a" A? "b" at index 0 (aaabbbccc)
Initiating parse: "a" at index 0 (aaabbbccc)
Result for "a" at index 0 (aaabbbccc) => "a"
Initiating parse: A? at index 1 (aabbbccc)
Result for A? at index 1 (aabbbccc) => nil
Initiating parse: "b" at index 1 (aabbbccc)
No result for "b" at index 1 (aabbbccc)
Initiating parse: A at index 1 (aabbbccc)
Initiating parse: "a" A? "b" at index 1 (aabbbccc)
Initiating parse: "a" at index 1 (aabbbccc)
Result for "a" at index 1 (aabbbccc) => "a"
Initiating parse: A? at index 2 (abbbccc)
Result for A? at index 2 (abbbccc) => nil
Initiating parse: "b" at index 2 (abbbccc)
No result for "b" at index 2 (abbbccc)
Initiating parse: A at index 2 (abbbccc)
Initiating parse: "a" A? "b" at index 2 (abbbccc)
Initiating parse: "a" at index 2 (abbbccc)
Result for "a" at index 2 (abbbccc) => "a"
Initiating parse: A? at index 3 (bbbccc)
Result for A? at index 3 (bbbccc) => nil
Initiating parse: "b" at index 3 (bbbccc)
Result for "b" at index 3 (bbbccc) => "b"
Result for "a" A? "b" at index 2 (abbbccc) => ("a" "b")
Result for A at index 2 (abbbccc) => [:A "a" "b"]
Result for A? at index 2 (abbbccc) => [:A "a" "b"]
Initiating parse: "b" at index 4 (bbccc)
Result for "b" at index 4 (bbccc) => "b"
Result for "a" A? "b" at index 1 (aabbbccc) => ("a" [:A "a" "b"] "b")
Result for A at index 1 (aabbbccc) => [:A "a" [:A "a" "b"] "b"]
Result for A? at index 1 (aabbbccc) => [:A "a" [:A "a" "b"] "b"]
Initiating parse: "b" at index 5 (bccc)
Result for "b" at index 5 (bccc) => "b"
Result for "a" A? "b" at index 0 (aaabbbccc) => ("a" [:A "a" [:A "a" "b"] "b"] "b")
Result for A at index 0 (aaabbbccc) => [:A "a" [:A "a" [:A "a" "b"] "b"] "b"]
Initiating parse: "c" at index 6 (ccc)
Result for "c" at index 6 (ccc) => "c"
Result for A "c" at index 0 (aaabbbccc) => ([:A "a" [:A "a" [:A "a" "b"] "b"] "b"] "c")
Result for &(A "c") at index 0 (aaabbbccc) => nil
Initiating parse: "a"+ at index 0 (aaabbbccc)
Result for "a"+ at index 0 (aaabbbccc) => ("a")
Initiating full parse: B at index 1 (aabbbccc)
Initiating full parse: "b" B? "c" at index 1 (aabbbccc)
Result for "a"+ at index 0 (aaabbbccc) => ("a" "a")
Initiating full parse: B at index 2 (abbbccc)
Initiating full parse: "b" B? "c" at index 2 (abbbccc)
Result for "a"+ at index 0 (aaabbbccc) => ("a" "a" "a")
Initiating full parse: B at index 3 (bbbccc)
Initiating full parse: "b" B? "c" at index 3 (bbbccc)
Initiating parse: B? at index 4 (bbccc)
Result for B? at index 4 (bbccc) => nil
Initiating full parse: "c" at index 4 (bbccc)
No result for "c" at index 4 (bbccc)
Initiating parse: B at index 4 (bbccc)
Initiating parse: "b" B? "c" at index 4 (bbccc)
Initiating parse: B? at index 5 (bccc)
Result for B? at index 5 (bccc) => nil
Initiating parse: "c" at index 5 (bccc)
No result for "c" at index 5 (bccc)
Initiating parse: B at index 5 (bccc)
Initiating parse: "b" B? "c" at index 5 (bccc)
Initiating parse: B? at index 6 (ccc)
Result for B? at index 6 (ccc) => nil
Result for "b" B? "c" at index 5 (bccc) => ("b" "c")
Result for B at index 5 (bccc) => [:B "b" "c"]
Result for B? at index 5 (bccc) => [:B "b" "c"]
Initiating parse: "c" at index 7 (cc)
Result for "c" at index 7 (cc) => "c"
Result for "b" B? "c" at index 4 (bbccc) => ("b" [:B "b" "c"] "c")
Result for B at index 4 (bbccc) => [:B "b" [:B "b" "c"] "c"]
Result for B? at index 4 (bbccc) => [:B "b" [:B "b" "c"] "c"]
Initiating full parse: "c" at index 8 (c)
Result for "c" at index 8 (c) => "c"
Result for "b" B? "c" at index 3 (bbbccc) => ("b" [:B "b" [:B "b" "c"] "c"] "c")
Result for B at index 3 (bbbccc) => [:B "b" [:B "b" [:B "b" "c"] "c"] "c"]
Result for &(A "c") "a"+ B at index 0 (aaabbbccc) => ("a" "a" "a" [:B "b" [:B "b" [:B "b" "c"] "c"] "c"])
Result for S at index 0 (aaabbbccc) => [:S "a" "a" "a" [:B "b" [:B "b" [:B "b" "c"] "c"] "c"]]
Successful parse.
Profile:  {:create-node 43, :push-full-listener 10, :push-stack 43, :push-listener 42, :push-result 38, :push-message 45}
</pre>
</details>

However, it's not necessarily easy to distinguish between partial attempts and final parses here. Is there a way to capture the tracing information as part of the parse tree or otherwise as a form of structured data instead of as flat logs? I think that could help me build what I'm looking for here.

Sorry if the overall question seems kind of vague - I've learned a lot about parsing and EBNF through Instaparse, but I may not have defined what I'm looking for clearly enough. Please let me know if I can clarify or give additional examples.

**Comment by Engelberg** [comment]
You're right that lookaheads don't show up in the parse tree, because what makes them valuable is that they don't consume characters. Your idea to use the trace is clever.

I think the relevant lines you are looking for are:
```
Result for A at index 2 (abbbccc) => [:A "a" "b"]
Result for A at index 1 (aabbbccc) => [:A "a" [:A "a" "b"] "b"]
Result for A at index 0 (aaabbbccc) => [:A "a" [:A "a" [:A "a" "b"] "b"] "b"]
```

Tracing currently builds a log of strings, but if you really need it as a data structure you could fork your own version of instaparse and change the calls to `log` in gll.cljc from something like:

```
  (log tramp (format "Initiating parse: %s at index %d (%s)"
                     (print/combinators->str parser) index
                     (string-context (:text tramp) index)))
```

to 

```
  (log tramp [:initiating 
                     (print/combinators->str parser) index
                     (string-context (:text tramp) index)])
```

and then optionally change the `log` macro to conj these data structures into some atom, rather than printing them to the screen.

**Comment by respatialized** [comment]
Gotcha, thanks! For the time being, I think I might go for an easier hack - rebinding `*out*` during `:trace true` and then parsing the logs (luckily, there's a library to make that part a breeze).

If I eventually found it necessary to create a fork for this capability, would you be willing to accept a PR? The "trace as data" capability could be enabled without affecting the default behavior by using another keyword value for `:trace` instead of `true` - something like `:trace :data`.
