### ISSUE TITLE
Clojure does have raw strings

### ISSUE THREAD

**Issue by whamtet** [Engelberg/instaparse#215]
Thanks for the excellent library, well documented as well.  README.md notes that

"It is unfortunate that this extra level of escaping is necessary. Many programming languages provide some sort of facility for creating "raw strings" which are taken verbatim (e.g., Python's triple-quoted strings). I don't understand why Clojure does not support raw strings, but it doesn't."

However a workaround is to declare the grammar in a regex.

```clojure
(insta/parser (str #"S = #'\s*' 'a' #'\s*'"))
```

In fact we could even add the option for `insta/parser` to accept regex and just wrap that in str internally.  Happy to submit a PR if you agree.

**Comment by Engelberg** [comment]
Funny, I had forgotten that I expressed that opinion in the README. At this point, I'm used to the escaping rules, but I remember now it bugged me at the time.

Your workaround is very clever. I see what you're saying that you could save a half-dozen characters by allowing `insta/parser` to automatically convert regexes to strings, but I don't think I want that to happen so invisibly to the user. I already see a fair amount of confusion/questions surrounding the distinction of strings vs regexes as tokens in the grammar, and I fear that if I were to encourage wrapping the whole grammar string in a regex when you're not really using it as a regex will cause even more confusion. Probably better for users to understand that they are building a regex and then extracting the regex's internal string representation manually with `str`. A nifty trick! Thanks for sharing.

**Comment by whamtet** [comment]
Ok, you could mention it in the docs!
