### ISSUE TITLE
Regex for unicode characters by code point

### ISSUE THREAD

**Issue by getify** [Engelberg/instaparse#218]
I've been using [a helpful web tool](https://mdkrajnak.github.io/ebnftest/) that utilized a Clojurescript port of instaparse. Their web tool lets me author/test productions in a browser web page (which I've found very convenient, especially when collaborating with others).

Unfortunately, I'm having a problem with some regex needs. I was using a syntax I believe to be valid for Clojure/Java regexes, specifically for specifying unicode characters by code point.

Details of my issue are here: https://github.com/mdkrajnak/ebnftest/issues/1

I wanted to cross-post here in case you might share some insight (or any links you may have) into what specific regex syntax I need to use? Thank you.

**Comment by Engelberg** [comment]
On Clojure, instaparse is using Java regexes. I'm less familiar with the Clojurescript port, but it wouldn't surprise me if the Clojurescript port uses whatever regexes are supported by Javascript, specifically whatever is supported by the Google Closure compiler utilized by clojurescript.

**Comment by Engelberg** [comment]
I can't think of anything beyond whatever clojurescript does.

**Comment by getify** [comment]
I worked around my issue by not using a regex and just including the string literal characters in my productions.
