### ISSUE TITLE
Possible to export the generated parser (as JS)?

### ISSUE THREAD

**Issue by getify** [Engelberg/instaparse#219]
I have an EBNF grammar for a new programming language I'm writing. When I use the clojurescript port of instaparse to parse this grammar, it takes the JS engine (v8, in chrome or node) about 2 seconds to build the parser. It seems once the parser is built, it's extremely fast at parsing/checking input strings (of short to moderate length).

The grammar is fairly stable now, and I don't expect it to change much. So instead of re-generating the parser to check each test input string, I was wondering if it's possible for me to "export" the generated parser (the clojurescript/JS code itself) so that I can just reuse that?

What I mean is, "export" the clojurescript generated parser as a JS function (that I could store in a file), so that I could just re-execute that with a different test input string. Alternatively, perhaps I could export it as Clojure or Clojurescript, and then do a conversion step on that code to JS.

I don't really know much about Clojure/Clojurescript, so I'm not sure if something like that is even possible. But just figured I would explore the options. Thanks for any pointers you may be able to provide.

**Comment by Engelberg** [comment]
Have you tried the `defparser` option as documented here? https://github.com/engelberg/instaparse#defparser

That should help.

**Comment by getify** [comment]
Thank you. I had read about that, but it seemed like it was just generating the parser ahead of time and it wasn't clear to me (as I'm not familiar with Clojure/Clojurescript) that it was producing some sort of serialization of the parser that I could save and externalize (like in a JS file).

I will look into it further. Thank you for the tip.

**Comment by Engelberg** [comment]
It's not serializing it, but it is doing the most computationally intensive portion at compile-time.

**Comment by getify** [comment]
OK. Thanks again.
