### ISSUE TITLE
Proposal: starting line and column

### ISSUE THREAD

**Issue by mainej** [Engelberg/instaparse#223]
Per No. 10 in your [Performance tips](https://github.com/Engelberg/instaparse/blob/master/docs/Performance.md#performance-tips) I have a parsing job that would be more efficient if the document was first split into smaller chunks. I'd like to add line and column metadata after parsing the chunks, but I want the line numbers to be relative to the start of the document, not the start of the chunk.

To facilitate that, I'd like to propose a new arity for `instaparse.line-col/add-line-col-spans` that accepts the starting line and column:

```clojure
(defn add-line-col-spans
  ([text parse-tree] (add-line-col-spans text parse-tree 1 1))
  ([text parse-tree start-line start-column]
   ...))
```

I have an implementation ready, so if you'd like I can submit a PR.

**Comment by Engelberg** [comment]
Thanks to support from Clojurists Together, I've been able to finally make time to review instaparse pull requests from the past couple of years. This is a great suggestion and I'll be incorporating this into the next release coming within a couple of weeks. Thanks for contributing the idea and the pull request.

**Comment by mainej** [comment]
Glad that you got some time from Clojurists Together. Thanks for considering the PR!
