### ISSUE TITLE
Unexpected character span when parsing with :auto-whitespace

### ISSUE THREAD

**Issue by wpeers** [Engelberg/instaparse#227]
- Using `instaparse` version `1.4.12`

Given following parser and a string containing whitespace:
```clojure
(def as-and-bs
  (insta/parser
    "S = AB*
     AB = A B
     A = a+
     B = b+" :auto-whitespace :standard))

(as-and-bs "aaaaa  bbbaaaabb")
=> [:S [:AB [:A "a" "a" "a" "a" "a"] [:B "b" "b" "b"]] [:AB [:A "a" "a" "a" "a"] [:B "b" "b"]]]
```
retrieving the span for :B yields `[5 10]`:
```clojure
(-> (as-and-bs "aaaaa  bbbaaaabb")
    second
    (nth 2)
    insta/span)
=> [5 10]
```
I would have expected `=> [7 10]` since the match for `:B` (i.e. "bbb") is only 3 characters long.

**Comment by Engelberg** [comment]
This has to do with the way auto-whitespace adds a whitespace portion to each rule, so B has been modified so it isn't looking solely for b's. The whitespace therefore ends up as part of its span.
