### ISSUE TITLE
Include clj-kondo config

### ISSUE THREAD

**Issue by toniz4** [Engelberg/instaparse#231]
Some functions coming from `instaparse.core` are seen as unresolved by clj-kondo, like `transform` and `span`. This happens because clj-kondo doesn't expand macros, and since those symbols are defined with `defclone`, clj-kondo considers them undefined. It's a false negative, but It would be nice if we did not need to manually suppress those errors.

We would only need to add a config.edn file as described by the [clj-kondo documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#exporting-and-importing-configuration)

If it's something you wish to add, I will be happy to make a PR.

**Comment by Engelberg** [comment]
Yes, I'd be happy to include this, and the timing is great as I'm about to spend some time on instaparse pull requests. I haven't used clj-kondo myself, so if you're willing to make a PR, that would be appreciated.
