### ISSUE TITLE
Online playground

### ISSUE THREAD

**Issue by stereobooster** [Engelberg/instaparse#233]
HI. I was wondering, if it is possible to create online playground to experiment with different grammars without need to install anything. It should be possible to use library with ClojureScript, right? (I don't know). And there are online ClojureScript REPLs. It can be hosted using github pages (or Netlify).

WDYT?

**Comment by Engelberg** [comment]
Check out https://github.com/mhuebert/instaparse-live and https://instaparse-live.matt.is/

**Comment by stereobooster** [comment]
Thank you

**Comment by stereobooster** [comment]
I created my own version. Maybe not full featured, but it shows visualization of the tree. https://instaparsejs.stereobooster.com/

<img width="1191" alt="Screenshot" src="https://github.com/user-attachments/assets/7b6d19bd-b087-4d6d-9682-42afbdd469ab">
