### ISSUE TITLE
Line and Column metadata

### ISSUE THREAD

**Issue by brandonbloom** [Engelberg/instaparse#42]
I noticed that the parse trees have begin and end position metadata, but not line and column data. Failures seem to re-create line and column metadata via re-walking the input string. It would be great if I could optionally enable line and column tracking during parsing, such that all parse results were fully decorated after the parse completes. Bonus points for begin/end line/column pairs.

**Comment by Engelberg** [comment]
Followed clojj's suggestion and added a new function in version 1.4.1 `add-line-and-column-info-to-metadata` which decorates the result tree with start and end line and column metadata.  This avoids the performance hit of trying to calculate all the newlines that are processed by regular expressions during intermediate parses, most of which get discarded along the way to finding the correct parse.  It is able to do the line/column annotation with one additional pass through the input string, and one traversal over the result tree.

Documentation is here: [https://github.com/engelberg/instaparse#line-and-column-information](https://github.com/engelberg/instaparse#line-and-column-information)

**Comment by Engelberg** [comment]
@brandonbloom, in line with your original proposal, I'm still considering the possibility of adding a flag to the parser, something like `:line-column true` which would automatically do this post-processing step.

That would be a nice convenience, but I also like the transparency that this API provides in terms of how much extra work needs to be done behind the scenes to add the line-column info, and furthermore, it gives you the added capability of waiting to process the result tree until after it has been partially transformed by insta/transform (line/column info will be added anywhere that the span metadata still exists in the transformed tree).  If you're going to be collapsing a bunch of nodes, you can gain additional efficiency by adding the line/column info after doing the tree transformation.

I would like your opinion on whether a flag like `:line-column true` to the parser would still add sufficient convenience value above and beyond this more decomplected API to make it worth doing.

**Comment by brandonbloom** [comment]
Given the generality of the algorithm and its non-streaming nature, the extra-pass to line/column information seems perfectly reasonable. A convenience flag would be nice.
