### ISSUE TITLE
Add positional metadata to parse tree

### ISSUE THREAD

**Issue by Engelberg** [Engelberg/instaparse#8]
Request from David Powell to add either character number of line/column info as metadata.

**Comment by muhuk** [comment]
Normally metadata is like:

    {:instaparse.gll/start-index 0, :instaparse.gll/end-index 43}

The result of `instaparse.line-col/add-line-col-spans`:

    {:instaparse.gll/start-index 0, :instaparse.gll/end-index 43, :instaparse.gll/start-line 1, :instaparse.gll/start-column 1, :instaparse.gll/end-line 1, :instaparse.gll/end-column 44}
