### ISSUE TITLE
Raw strings regex escaping

### ISSUE THREAD

**Issue by clojens** [Engelberg/instaparse#81]
I noticed your comment on the regex double backslash escaping one has to do in Clojure and decided to look into this for a bit. There seems to be a way to avoid this, perhaps this can be used with instaparse, I'm not sure but in case it does:

```clojure
(java.util.regex.Pattern/quote "\r\n?|\n")
;"\\Q\r\n?|\n\\E"
```

**Comment by Engelberg** [comment]
As far as I can tell, this doesn't just escape backslashes, but changes the entire meaning of the regular expression, making it treat the whole thing literally.  So probably not applicable.
