### ISSUE TITLE
Call to LispReader$StringReader breaks with feature expressions patch

### ISSUE THREAD

**Issue by MichaelBlume** [Engelberg/instaparse#90]
This may be a premature issue, but I thought a heads-up might be useful; the feature expressions patch under discussion for inclusion in Clojure 1.7.0 changes the arity of LispReader$StringReader objects when they are called as functions, causing instaparse's safe-read-string to crash. I reported this on the clojure development board and the response was basically that this was deep enough in Clojure internals that it should be expected to break.

http://dev.clojure.org/jira/browse/CLJ-1424

**Comment by Engelberg** [comment]
Thanks for the heads up.  Fortunately, it sounds like if it's just an arity change, it will be easy to fix when the time comes.

**Comment by MichaelBlume** [comment]
Update: This is in 1.7.0-alpha6

**Comment by bitnovus** [comment]
@MichaelBlume 
Thanks for the update.

@Engelberg 
We'd love to see this issue resolved soon! We use Instaparse through Compojure and our builds are breaking with Clojure 1.7.0-alpha6. Thanks for your hard work!

**Comment by kanwei** [comment]
+1

**Comment by seancorfield** [comment]
Yes, another +1 here -- this just broke our build since we routinely test against Clojure master (which now includes the changes from Alpha 6).

**Comment by seancorfield** [comment]
Confirmed this works with Clojure master now for our unit tests. Thank you! Next step is to upgrade our whole stack to Clojure 1.7.0-alpha6 and run a full stack test.
