### ISSUE TITLE
serialization in clojurescript

### ISSUE THREAD

**Issue by rothfield** [Engelberg/instaparse#93]
I've got my parser running in clojurescript.  The startup time is long, so I want to serialize it. On the cljs fork's readme it says:

"You can serialize an instaparse parser with print-dup, and deserialize it with read. (You can't use clojure.edn/read because edn does not support regular expressions.)"

Can you give me an example of how to do this?

**Comment by Engelberg** [comment]
In the Clojure version of instaparse, the result of

    => (with-out-str (print-dup instaparse.test/as-and-bs-regex *out*))

is

"#instaparse.core.Parser[{:S {:red {:reduction-type :hiccup, :key :S}, :tag :star, :parser {:tag :nt, :keyword :AB}}, :AB {:red {:reduction-type :hiccup, :key :AB}, :tag :cat, :parsers ({:tag :nt, :keyword :A} {:tag :nt, :keyword :B})}, :A {:red {:reduction-type :hiccup, :key :A}, :tag :plus, :parser {:tag :regexp, :regexp #\"a\"}}, :B {:red {:reduction-type :hiccup, :key :B}, :tag :plus, :parser {:tag :regexp, :regexp #\"b\"}}}, :S, :hiccup]"

You can read this back in with `clojure.core/read-string`.  However, as far as I know, Clojurescript does not have a comparable read-string function.  The only read-string available handles a weaker subset of what Clojure can represent, i.e., the edn format.

Check out the first answer in this stackoverflow thread http://stackoverflow.com/questions/24661655/clojure-clojurescript-clojure-core-read-string-clojure-edn-read-string-and-c

I don't actually maintain the Clojurescript port (and have never actually used it myself), so if you have further questions or want ideas about startup time, you could follow up on the port's github page with Lucas Bradstreet.

**Comment by Engelberg** [comment]
One idea: Take a look at the grammar map in your parser with (:grammar parser).  The parser constructor can also take a grammar map, so just copying and pasting this grammar into your code, and using this rather than the string representation of your grammar to build the parser might give you a faster startup time, because then it doesn't need to parse your string into a grammar map.

**Comment by Engelberg** [comment]
For example:

```clojure
(def as-and-bs-regex
  (insta/parser
    "S = AB*
     AB = A B
     A = #'a'+
     B = #'b'+"))
```

=> (:grammar as-and-bs-regex)

{:S {:red {:reduction-type :hiccup, :key :S}, :tag :star, :parser {:tag :nt, :keyword :AB}}, :AB {:red {:reduction-type :hiccup, :key :AB}, :tag :cat, :parsers ({:tag :nt, :keyword :A} {:tag :nt, :keyword :B})}, :A {:red {:reduction-type :hiccup, :key :A}, :tag :plus, :parser {:tag :regexp, :regexp #"a"}}, :B {:red {:reduction-type :hiccup, :key :B}, :tag :plus, :parser {:tag :regexp, :regexp #"b"}}}

So, I can replace my as-and-bs-regex with:

(def as-and-bs-regex (insta/parser {:S {:red {:reduction-type :hiccup, :key :S}, :tag :star, :parser {:tag :nt, :keyword :AB}}, :AB {:red {:reduction-type :hiccup, :key :AB}, :tag :cat, :parsers ({:tag :nt, :keyword :A} {:tag :nt, :keyword :B})}, :A {:red {:reduction-type :hiccup, :key :A}, :tag :plus, :parser {:tag :regexp, :regexp #"a"}}, :B {:red {:reduction-type :hiccup, :key :B}, :tag :plus, :parser {:tag :regexp, :regexp #"b"}}}
:start :S))
