### ISSUE TITLE
New lines are not working for visualisation tree with spans

### ISSUE THREAD

**Issue by mishadoff** [Engelberg/instaparse#96]
```(insta/visualize (insta/parse parser "1+2"))```

Produces following picture

![](http://i.imgur.com/Lgkdo1W.png)

Seems redundant escaping for new-line character, broken here https://github.com/Engelberg/instaparse/commit/da205db78ac4df84ea46f9238862131b27aac04e

Is there a purpose for escaping `\n`?

**Comment by Engelberg** [comment]
The extra escaping was a workaround for a problem with Rhizome in rhizome versions 0.2.4 and before.  Now that the problem with Rhizome is fixed, the extra escaping causes problems.

I have deployed a new Instaparse 1.4.0-SNAPSHOT that does the right thing depending on which version of Rhizome you are using.

If you can't use the new snapshot and need to stay on 1.3.6 for some reason, then you should use Rhizome version 0.2.4 or before.
