### ISSUE TITLE
Handling optional whitespace separator?

### ISSUE THREAD

**Issue by alex-glv** [Engelberg/instaparse#99]
Hi,

I am not sure if this is the right place to ask. I am importing a language definition from a yacc file and it seems that it doesn't explicitly state that whitespace is to be ignored universally throughout the source code. Is there a way I can define such a rule within instaparse?

Say,

```
class ClassName {
  ... statements 
}
```

I want an optional whitespace between '{' and ... statements to be implicitly expected.

Hope that makes sense, thank you!

**Comment by Engelberg** [comment]
You might this experimental feature to be useful for your use case:

https://github.com/Engelberg/instaparse/blob/master/docs/ExperimentalFeatures.md#auto-whitespace

**Comment by Engelberg** [comment]
The simplest way is to add `:auto-whitespace :standard` to your creation of the parser.  This isn't always what you want for every grammar, but it sounds like this is what you need in your case.

**Comment by alex-glv** [comment]
Just found the experimental feature and playing around with it... Thanks a lot!
